export const weeklyAvailability = {
  reports: [
    {
      date: "2026-05-01",
      label: "1 May 2026",
      programme: "EMMS",
      available: 218,
      total: 477,
      unavailable: 259,
      availability: 0.457,
      categories: [
        ["VACCINES", 0, 2, 0],
        ["GLOVES", 0, 4, 0],
        ["COTTON WOOL, DRESSING, SWABS & BANDAGES", 1, 9, 0.1111],
        ["DERMATOLOGICAL/TOPICAL MEDICINES", 1, 7, 0.1429],
        ["ANTIINFECTIVE MEDICINES", 6, 35, 0.1714],
        ["ANTIDOTES AND OTHER SUBSTANCES USED IN POISONINGS", 1, 5, 0.2],
        ["ANTINEOPLASTICS AND IMMUNOMODULATORS", 6, 24, 0.25],
        ["IMAGING", 2, 8, 0.25],
        ["EPIDEMIC SUPPLIES", 8, 27, 0.2963],
        ["SUTURES", 6, 20, 0.3],
        ["CONSUMABLES", 9, 28, 0.3214],
        ["MUSCLE RELAXANTS (PERIPHERALLY-ACTING) AND CHOLINESTERASE INHIBITORS", 2, 6, 0.3333],
        ["ANTISEPTICS AND DISINFECTANTS", 2, 6, 0.3333],
        ["MEDICINES FOR DISEASES OF JOINTS & BONES", 1, 3, 0.3333],
        ["ANAESTHETICS, PREOPERATIVE MEDICINES AND MEDICAL GASES", 3, 8, 0.375],
        ["ANTIALLERGICS AND MEDICINES USED IN ANAPHYLAXIS", 3, 8, 0.375],
        ["GENERAL MED-SURG", 5, 13, 0.3846],
        ["MEDICINES FOR TREATMENT OF OPPORTUNISTIC INFECTIONS", 3, 7, 0.4286],
        ["CARDIOVASCULAR MEDICINES", 9, 20, 0.45],
        ["ANTICONVULSANTS/ANTIEPILEPTICS/ANXIOLYTICS", 5, 11, 0.4545],
        ["MEDICINES FOR PAIN AND PALLIATIVE CARE", 6, 12, 0.5],
        ["DIURETICS", 3, 6, 0.5],
        ["MEDICINES FOR DIABETES/ACTING ON ENDOCRINE", 4, 8, 0.5],
        ["VITAMINS AND MINERALS", 3, 6, 0.5],
        ["SYRINGES AND NEEDLES", 4, 8, 0.5],
        ["GASTROINTESTINAL MEDICINES", 5, 9, 0.5556],
        ["DENTAL", 5, 9, 0.5556],
        ["ANTIMALARIAL", 4, 7, 0.5714],
        ["SOLUTIONS CORRECTING WATER, ELECTROLYTE AND ACID-BASE DISTURBANCES", 4, 7, 0.5714],
        ["IV CANNULAE & GIVING SETS", 4, 7, 0.5714],
        ["MEDICINES ACTING ON THE RESPIRATORY TRACT", 3, 5, 0.6],
        ["ANTIRETROVIRAL THERAPY MEDICINES", 10, 16, 0.625],
        ["MEDICINES FOR MENTAL AND BEHAVIOURAL DISORDERS", 10, 16, 0.625],
        ["MEDICINES AFFECTING THE BLOOD", 4, 6, 0.6667],
        ["MEDICINES FOR REPRODUCTIVE HEALTH AND PERINATAL CARE", 12, 18, 0.6667],
        ["ANTITUBERCULOSIS AND ANTILEPROSY MEDICINES", 17, 24, 0.7083],
        ["RENAL", 38, 53, 0.717],
        ["MEDICINES USED IN DIARRHOEA", 2, 2, 1],
        ["CONDOMS", 2, 2, 1],
        ["NUTRITIONAL PRODUCTS", 5, 5, 1],
      ],
    },
    {
      date: "2026-05-08",
      label: "8 May 2026",
      programme: "EMMS",
      available: 220,
      total: 477,
      unavailable: 257,
      availability: 0.4612,
      categories: [
        ["VACCINES", 0, 2, 0],
        ["GLOVES", 0, 4, 0],
        ["COTTON WOOL, DRESSING, SWABS & BANDAGES", 1, 9, 0.1111],
        ["DERMATOLOGICAL/TOPICAL MEDICINES", 1, 7, 0.1429],
        ["ANTIINFECTIVE MEDICINES", 6, 35, 0.1714],
        ["ANTIDOTES AND OTHER SUBSTANCES USED IN POISONINGS", 1, 5, 0.2],
        ["ANTINEOPLASTICS AND IMMUNOMODULATORS", 6, 24, 0.25],
        ["IMAGING", 2, 8, 0.25],
        ["EPIDEMIC SUPPLIES", 8, 27, 0.2963],
        ["SUTURES", 6, 20, 0.3],
        ["CONSUMABLES", 9, 28, 0.3214],
        ["MUSCLE RELAXANTS (PERIPHERALLY-ACTING) AND CHOLINESTERASE INHIBITORS", 2, 6, 0.3333],
        ["ANTISEPTICS AND DISINFECTANTS", 2, 6, 0.3333],
        ["MEDICINES FOR DISEASES OF JOINTS & BONES", 1, 3, 0.3333],
        ["ANAESTHETICS, PREOPERATIVE MEDICINES AND MEDICAL GASES", 3, 8, 0.375],
        ["ANTIALLERGICS AND MEDICINES USED IN ANAPHYLAXIS", 3, 8, 0.375],
        ["GENERAL MED-SURG", 5, 13, 0.3846],
        ["MEDICINES FOR TREATMENT OF OPPORTUNISTIC INFECTIONS", 3, 7, 0.4286],
        ["CARDIOVASCULAR MEDICINES", 9, 20, 0.45],
        ["ANTICONVULSANTS/ANTIEPILEPTICS/ANXIOLYTICS", 5, 11, 0.4545],
        ["MEDICINES FOR PAIN AND PALLIATIVE CARE", 6, 12, 0.5],
        ["DIURETICS", 3, 6, 0.5],
        ["MEDICINES FOR DIABETES/ACTING ON ENDOCRINE", 4, 8, 0.5],
        ["SYRINGES AND NEEDLES", 4, 8, 0.5],
        ["GASTROINTESTINAL MEDICINES", 5, 9, 0.5556],
        ["DENTAL", 5, 9, 0.5556],
        ["ANTIMALARIAL", 4, 7, 0.5714],
        ["SOLUTIONS CORRECTING WATER, ELECTROLYTE AND ACID-BASE DISTURBANCES", 4, 7, 0.5714],
        ["IV CANNULAE & GIVING SETS", 4, 7, 0.5714],
        ["MEDICINES ACTING ON THE RESPIRATORY TRACT", 3, 5, 0.6],
        ["ANTIRETROVIRAL THERAPY MEDICINES", 10, 16, 0.625],
        ["MEDICINES FOR MENTAL AND BEHAVIOURAL DISORDERS", 10, 16, 0.625],
        ["MEDICINES FOR REPRODUCTIVE HEALTH AND PERINATAL CARE", 12, 18, 0.6667],
        ["VITAMINS AND MINERALS", 4, 6, 0.6667],
        ["ANTITUBERCULOSIS AND ANTILEPROSY MEDICINES", 17, 24, 0.7083],
        ["RENAL", 38, 53, 0.717],
        ["MEDICINES AFFECTING THE BLOOD", 5, 6, 0.8333],
        ["MEDICINES USED IN DIARRHOEA", 2, 2, 1],
        ["CONDOMS", 2, 2, 1],
        ["NUTRITIONAL PRODUCTS", 5, 5, 1],
      ],
    },
    {
      date: "2026-05-15",
      label: "15 May 2026",
      programme: "EMMS",
      available: 213,
      total: 477,
      unavailable: 264,
      availability: 0.4465,
      categories: [
        ["VACCINES", 0, 2, 0],
        ["GLOVES", 0, 4, 0],
        ["COTTON WOOL, DRESSING, SWABS & BANDAGES", 1, 9, 0.1111],
        ["DERMATOLOGICAL/TOPICAL MEDICINES", 1, 7, 0.1429],
        ["ANTIINFECTIVE MEDICINES", 5, 35, 0.1429],
        ["ANTIDOTES AND OTHER SUBSTANCES USED IN POISONINGS", 1, 5, 0.2],
        ["ANTINEOPLASTICS AND IMMUNOMODULATORS", 6, 24, 0.25],
        ["IMAGING", 2, 8, 0.25],
        ["ANTIALLERGICS AND MEDICINES USED IN ANAPHYLAXIS", 2, 8, 0.25],
        ["EPIDEMIC SUPPLIES", 7, 27, 0.2593],
        ["SUTURES", 6, 20, 0.3],
        ["CONSUMABLES", 9, 28, 0.3214],
        ["MUSCLE RELAXANTS (PERIPHERALLY-ACTING) AND CHOLINESTERASE INHIBITORS", 2, 6, 0.3333],
        ["ANTISEPTICS AND DISINFECTANTS", 2, 6, 0.3333],
        ["MEDICINES FOR DISEASES OF JOINTS & BONES", 1, 3, 0.3333],
        ["ANAESTHETICS, PREOPERATIVE MEDICINES AND MEDICAL GASES", 3, 8, 0.375],
        ["GENERAL MED-SURG", 5, 13, 0.3846],
        ["MEDICINES FOR PAIN AND PALLIATIVE CARE", 5, 12, 0.4167],
        ["MEDICINES FOR TREATMENT OF OPPORTUNISTIC INFECTIONS", 3, 7, 0.4286],
        ["ANTIMALARIAL", 3, 7, 0.4286],
        ["CARDIOVASCULAR MEDICINES", 9, 20, 0.45],
        ["ANTICONVULSANTS/ANTIEPILEPTICS/ANXIOLYTICS", 5, 11, 0.4545],
        ["DIURETICS", 3, 6, 0.5],
        ["MEDICINES FOR DIABETES/ACTING ON ENDOCRINE", 4, 8, 0.5],
        ["SYRINGES AND NEEDLES", 4, 8, 0.5],
        ["GASTROINTESTINAL MEDICINES", 5, 9, 0.5556],
        ["DENTAL", 5, 9, 0.5556],
        ["SOLUTIONS CORRECTING WATER, ELECTROLYTE AND ACID-BASE DISTURBANCES", 4, 7, 0.5714],
        ["IV CANNULAE & GIVING SETS", 4, 7, 0.5714],
        ["MEDICINES ACTING ON THE RESPIRATORY TRACT", 3, 5, 0.6],
        ["ANTIRETROVIRAL THERAPY MEDICINES", 10, 16, 0.625],
        ["MEDICINES FOR MENTAL AND BEHAVIOURAL DISORDERS", 10, 16, 0.625],
        ["ANTITUBERCULOSIS AND ANTILEPROSY MEDICINES", 15, 24, 0.625],
        ["MEDICINES FOR REPRODUCTIVE HEALTH AND PERINATAL CARE", 12, 18, 0.6667],
        ["VITAMINS AND MINERALS", 4, 6, 0.6667],
        ["RENAL", 38, 53, 0.717],
        ["MEDICINES AFFECTING THE BLOOD", 5, 6, 0.8333],
        ["MEDICINES USED IN DIARRHOEA", 2, 2, 1],
        ["CONDOMS", 2, 2, 1],
        ["NUTRITIONAL PRODUCTS", 5, 5, 1],
      ],
    },
    {
      date: "2026-05-08",
      label: "8 May 2026",
      programme: "LAB",
      available: null,
      total: null,
      unavailable: null,
      availability: 0.5121,
      categories: [
        ["Pipettes & Tips", null, null, 0],
        ["Biochemistry", null, null, 0.12],
        ["Acids & Alcochols", null, null, 0.25],
        ["Microbiology & Parasitology", null, null, 0.31],
        ["Haematology & Blood Transfusion", null, null, 0.32],
        ["Histopthology & Cytology", null, null, 0.36],
        ["General Labs", null, null, 0.4],
        ["Specimen Containers", null, null, 0.5],
        ["RDTs", null, null, 0.57],
        ["Microscope Slides & Coverslips", null, null, 0.67],
        ["CD4 Testing", null, null, 0.67],
        ["Infection Prevention Products", null, null, 1],
        ["Gene Xpert", null, null, 1],
        ["HIV Test Kits", null, null, 1],
      ],
    },
    {
      date: "2026-05-15",
      label: "15 May 2026",
      programme: "LAB",
      available: null,
      total: null,
      unavailable: null,
      availability: 0.4979,
      categories: [
        ["Pipettes & Tips", null, null, 0],
        ["Biochemistry", null, null, 0.21],
        ["Acids & Alcochols", null, null, 0.25],
        ["Microbiology & Parasitology", null, null, 0.27],
        ["Haematology & Blood Transfusion", null, null, 0.32],
        ["Histopthology & Cytology", null, null, 0.36],
        ["General Labs", null, null, 0.4],
        ["Specimen Containers", null, null, 0.5],
        ["RDTs", null, null, 0.57],
        ["Microscope Slides & Coverslips", null, null, 0.67],
        ["CD4 Testing", null, null, 0.67],
        ["HIV Test Kits", null, null, 0.75],
        ["Infection Prevention Products", null, null, 1],
        ["Gene Xpert", null, null, 1],
      ],
    },
  ],
  changes: {
    from: "1 May 2026",
    to: "8 May 2026",
    programme: "EMMS",
    newlyUnavailable: [],
    recovered: [
      { item: "Ferrous Sulphate", category: "MEDICINES AFFECTING THE BLOOD" },
      { item: "Multivitamin", category: "VITAMINS AND MINERALS" },
    ],
  },
  changesByProgramme: {
    EMMS: [
      {
        from: "1 May 2026",
        to: "8 May 2026",
        newlyUnavailable: [],
        recovered: [
          { item: "Ferrous Sulphate", category: "MEDICINES AFFECTING THE BLOOD" },
          { item: "Multivitamin", category: "VITAMINS AND MINERALS" },
        ],
      },
      {
        from: "8 May 2026",
        to: "15 May 2026",
        newlyUnavailable: [
          { item: "Linezolid", category: "ANTITUBERCULOSIS AND ANTILEPROSY MEDICINES" },
          { item: "Delamanid 50mg Tablet(672)", category: "ANTITUBERCULOSIS AND ANTILEPROSY MEDICINES" },
          { item: "Artemether + Lumefantrine 20/120 mg (12) Tab(30)", category: "ANTIMALARIAL" },
          { item: "Metronidazole tabs", category: "ANTIINFECTIVE MEDICINES" },
          { item: "Methylprednisolone", category: "ANTIALLERGICS AND MEDICINES USED IN ANAPHYLAXIS" },
          { item: "Pethidine Inj", category: "MEDICINES FOR PAIN AND PALLIATIVE CARE" },
          { item: "Disposable Head cover", category: "EPIDEMIC SUPPLIES" },
        ],
        recovered: [],
      },
    ],
    LAB: [
      {
        from: "8 May 2026",
        to: "15 May 2026",
        newlyUnavailable: [
          { item: "Standard Q HIV/Syphilis Combo", category: "HIV Test Kits" },
        ],
        recovered: [
          { item: "Biochemistry category improved", category: "Biochemistry" },
        ],
      },
    ],
  },
};
